name: WebApp Demo
on:
  push:
    branches:
      - 'main'
env:
  IMAGE_NAME_main: selwebapp-main
jobs:
  build-main:
    name: Build-main
    runs-on: [ubuntu-latest]
    if: github.ref_name == 'main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image 
        run: docker build -t ${{ env.IMAGE_NAME_main }} . 

      - name: Run Docker Container 
        run: docker run -d --name ${{ env.IMAGE_NAME_main }} -p 80:80 ${{ env.IMAGE_NAME_main }} 

      - name: Set script permissions 
        run: chmod +x ./testing/test.sh 

      - name: Run tests 
        run: ./testing/test.sh

      - name: Set up Docker environment 
        uses: docker/setup-buildx-action@v2

      - name: Login into registry
        if: success()
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZURE_ACR_ENDPOINT }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.AZURE_ACR_ENDPOINT }}/${{ env.IMAGE_NAME_main }}:${{ github.sha }}
            ${{ secrets.AZURE_ACR_ENDPOINT }}/${{ env.IMAGE_NAME_main }}:latest


